name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (apt)
      run: sudo apt install ninja-build libliquid-dev meson
    - name: compile (meson)
      run: meson setup -Dwerror=true build && cd build && meson compile
    - name: compile (makefile)
      run: make

  build-debian-oldoldstable:
    runs-on: ubuntu-latest
    container: debian:buster

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (apt-get)
      run: apt-get update && apt-get -y install build-essential libliquid-dev
    - name: compile (makefile)
      run: make EXTRA_CFLAGS="-Werror"

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies (apt)
      run: sudo apt install perl sox libliquid-dev
    - name: Download test data (git-lfs)
      run: git lfs pull
    - name: compile (makefile)
      run: make EXTRA_CFLAGS="-fsanitize=address,undefined"
    - name: run tests
      run: perl test/test.pl
